rebuild to get latest versions of packages
Remove vimdiff due to error observed in build:

    ERROR: unsatisfiable constraints:
      gvim-8.1.0829-r1:
        breaks: vimdiff-8.1.0829-r1[vim=8.1.0829-r1]
        satisfies: world[vim]
                   vimdiff-8.1.0829-r1[gvim=8.1.0829-r1]

Add libmaxminddb due to https://bugs.alpinelinux.org/issues/9988
libmindmaxdb replaces geoip.