install docker-compose via apk instead of pip to work around error
Resolve error seen in CI at
https://app.circleci.com/pipelines/github/jumanjihouse/devenv/19/workflows/c137730a-a251-482a-b1f6-5bf34ef3d1c6/jobs/169

    ERROR: Could not build wheels for pynacl which use PEP 517 and cannot be installed directly